POST http://localhost:3000/quotes
Content-Type: application/json

[
  {
    "pet": "dog",
    "years":  2,
    "breed" : "spaniel",
    "area" : "B63",
    "postcode" : "B633DP"
  },
  {
    "pet": "dog",
    "years":  2,
    "breed" : "spaniel",
    "area" : "B63",
    "postcode" : "B633DP"
  }
]

###

POST http://localhost:3000/quotes
Content-Type: application/json

[
  {
    "pet": "dog",
    "years":  10,
    "breed" : "spaniel",
    "area" : "B32",
    "postcode" : "B633DP"
  },
  {
    "pet": "dog",
    "years":  23,
    "breed" : "shih tzu",
    "area" : "SE23",
    "postcode" : "B633DP"
  }
]

